// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5rEzq9uQCGV5XOMt0N25NbNIJ5Fu3GU',
    appId: '1:843563095352:web:ae299a68648fb9ffe0ddcd',
    messagingSenderId: '843563095352',
    projectId: 'show-flow-app',
    authDomain: 'show-flow-app.firebaseapp.com',
    storageBucket: 'show-flow-app.firebasestorage.app',
    measurementId: 'G-E3CJ5G15Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB12IKrPAQR6MbCCc3cV1sHKq7eI1H97IE',
    appId: '1:843563095352:android:814d1ba2bf63d52ae0ddcd',
    messagingSenderId: '843563095352',
    projectId: 'show-flow-app',
    storageBucket: 'show-flow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAER6GMJgtnmOMOTRxy-KcU3eFcz9wuaws',
    appId: '1:843563095352:ios:5d9334e6f6b76807e0ddcd',
    messagingSenderId: '843563095352',
    projectId: 'show-flow-app',
    storageBucket: 'show-flow-app.firebasestorage.app',
    iosBundleId: 'com.example.groupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAER6GMJgtnmOMOTRxy-KcU3eFcz9wuaws',
    appId: '1:843563095352:ios:5d9334e6f6b76807e0ddcd',
    messagingSenderId: '843563095352',
    projectId: 'show-flow-app',
    storageBucket: 'show-flow-app.firebasestorage.app',
    iosBundleId: 'com.example.groupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL5rEzq9uQCGV5XOMt0N25NbNIJ5Fu3GU',
    appId: '1:843563095352:web:58e9e1e01985a3ade0ddcd',
    messagingSenderId: '843563095352',
    projectId: 'show-flow-app',
    authDomain: 'show-flow-app.firebaseapp.com',
    storageBucket: 'show-flow-app.firebasestorage.app',
    measurementId: 'G-72KLV5BMJQ',
  );
}
